apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    app.kubernetes.io/part-of: eks-gitops-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
